# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e357004fbf4719ed9cfb44603a4e4f5d25e4b128cc4348c95aef1b5da148efa2277a3bf5c2e6a4b2543e227e81e9954a8309d4ddb59a78816ab641064a4ac7df

test:
  secret_key_base: a312c94e6aca9219472676ef9625b245c82fa84fa799d452247d6fb36de7d7e921e1f1ae6f8d8f491f20e2e866f97c2bf54da4f6f0443ca0011516ca18be295c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
